# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets

from video_class import *
from utils import *

class Ui_Form(object):

    def close_window(self):
        QtCore.QCoreApplication.quit()
        # self.label.clear()
        # print('good jop')

    def mini_window(self):
        QtCore.

    def label(self):
        label1=self.lineEdit_2.text()
        label2=self.lineEdit_3.text()

        labels=[label1,label2]
        video.zh_label(labels)


    def title(self):

    def suntitle(self):

    def introdunction(self):


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1022, 732)
        self.top_vertical = QtWidgets.QWidget(Form)
        self.top_vertical.setGeometry(QtCore.QRect(9, 9, 1009, 720))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.top_vertical.setFont(font)
        self.top_vertical.setObjectName("top_vertical")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.top_vertical)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame_3 = QtWidgets.QFrame(self.top_vertical)
        self.horizontalFrame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalFrame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.icon = QtWidgets.QFrame(self.horizontalFrame_3)
        self.icon.setMinimumSize(QtCore.QSize(48, 48))
        self.icon.setStyleSheet("image: url(:/image/icon.jpg);")
        self.icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon.setObjectName("icon")
        self.horizontalLayout_4.addWidget(self.icon)
        spacerItem = QtWidgets.QSpacerItem(300, 40, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.remote_connect = QtWidgets.QPushButton(self.horizontalFrame_3)
        self.remote_connect.setObjectName("remote_connect")
        self.horizontalLayout_4.addWidget(self.remote_connect)
        self.pushButton = QtWidgets.QPushButton(self.horizontalFrame_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalFrame_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalFrame_3)
        self.pushButton_5.setWhatsThis("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.horizontalFrame_3)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout_4.addWidget(self.commandLinkButton)
        self.mini = QtWidgets.QPushButton(self.horizontalFrame_3)
        self.mini.setInputMethodHints(QtCore.Qt.ImhExclusiveInputMask)
        self.mini.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("components/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mini.setIcon(icon)
        self.mini.setIconSize(QtCore.QSize(32, 32))
        self.mini.setShortcut("")
        self.mini.setFlat(True)
        self.mini.setObjectName("mini")
        self.horizontalLayout_4.addWidget(self.mini)
        self.close = QtWidgets.QPushButton(self.horizontalFrame_3)
        self.close.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("components/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon1)
        self.close.setIconSize(QtCore.QSize(32, 32))
        self.close.setShortcut("")
        self.close.setFlat(True)
        self.close.setObjectName("close")
        self.horizontalLayout_4.addWidget(self.close)
        self.verticalLayout.addWidget(self.horizontalFrame_3)
        self.horizontalFrame = QtWidgets.QFrame(self.top_vertical)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame_3 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalFrame_3)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 451, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 20, 451, 511))
        self.tableWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_3.setGeometry(QtCore.QRect(0, 0, 301, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.listView = QtWidgets.QListView(self.tab_3)
        self.listView.setGeometry(QtCore.QRect(0, 0, 451, 521))
        self.listView.setObjectName("listView")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.verticalFrame_3)
        self.verticalFrame_2 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalFrame_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalFrame_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalFrame_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalFrame_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_5.addWidget(self.lineEdit_6)
        self.label_5 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.verticalFrame_2)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_5.addWidget(self.textBrowser_3)
        self.textEdit = QtWidgets.QTextEdit(self.verticalFrame_2)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_5.addWidget(self.textEdit)
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalFrame_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_5.addWidget(self.pushButton_9)
        self.gridLayout.addLayout(self.verticalLayout_5, 8, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalFrame_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalFrame_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalFrame_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalFrame_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalFrame_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_4.addWidget(self.lineEdit_5)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalFrame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.verticalFrame_2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_4.addWidget(self.comboBox)
        self.label_4 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalFrame_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_4.addWidget(self.comboBox_2)
        self.label_8 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.textEdit_2 = QtWidgets.QTextEdit(self.verticalFrame_2)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_4.addWidget(self.textEdit_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalFrame_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.gridLayout.addLayout(self.verticalLayout_4, 8, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.verticalFrame_2)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalFrame_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.verticalFrame_2)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.top_vertical)
        self.horizontalFrame_2.setMinimumSize(QtCore.QSize(1, 80))
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.horizontalFrame_2)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalFrame_2)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 1, 1, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.horizontalFrame_2)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_2.addWidget(self.textBrowser_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.horizontalFrame_2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.close.clicked.connect(self.wapper)
        self.submit.clicked.connect(video.edit_zh_label())



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.remote_connect.setToolTip(_translate("Form", "连接远程主机\n"
""))
        self.remote_connect.setText(_translate("Form", "remote server"))
        self.pushButton.setToolTip(_translate("Form", "管理解析地址和上传插件"))
        self.pushButton.setText(_translate("Form", "setting"))
        self.pushButton_8.setText(_translate("Form", "upload"))
        self.pushButton_5.setToolTip(_translate("Form", "一键以默认设置执行"))
        self.pushButton_5.setText(_translate("Form", "all in one"))
        self.commandLinkButton.setText(_translate("Form", "CommandLinkButton"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "title"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "url"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "length"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "loaded time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "video list"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "title"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "url"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "length"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "loaded time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "channel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "header-logo"))
        self.pushButton_2.setText(_translate("Form", "praser"))
        self.pushButton_3.setText(_translate("Form", "pytube"))
        self.pushButton_4.setText(_translate("Form", "edit"))
        self.label_2.setText(_translate("Form", "title"))
        self.label_5.setText(_translate("Form", "video subtitle"))
        self.pushButton_9.setText(_translate("Form", "save"))
        self.label.setText(_translate("Form", "video labels"))
        self.label_3.setText(_translate("Form", "header chice"))
        self.label_4.setText(_translate("Form", "logo chice"))
        self.label_8.setText(_translate("Form", "video introduction"))
        self.pushButton_6.setText(_translate("Form", "submit"))
        self.radioButton.setText(_translate("Form", "no title"))
        self.radioButton_2.setToolTip(_translate("Form", "using default label\\introduction"))
        self.radioButton_2.setText(_translate("Form", "default"))
        self.label_6.setText(_translate("Form", "local info"))
        self.label_7.setText(_translate("Form", "remote info"))

# import images_rc

if __name__=='__main__':
    import sys
    app=QtWidgets.QApplication(sys.argv)
    window=QtWidgets.QWidget()
    ui=Ui_Form()
    ui.setupUi(window)
    # window.setFixedHeight(700)
    # window.setFixedWidth(1000)
    window.setWindowFlags(Qt.FramelessWindowHint)

    window.show()

    app.exec_()
