# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
# from utilities import *
# from .. import utilities
# from ..utilities import video_list
# from local_version import utilities
# from .setting import Ui_Dialog

import os
import sys

sys.path.append(os.getcwd().replace('PyQt',''))
import utils
from PyQt import setting1

class Ui_Form(object):

    def label(self):
        label1=self.lineEdit_label1.text()
        label2=self.lineEdit_label2.text()
        label3=self.lineEdit_label3.text()
        label4=self.lineEdit_label4.text()
        label5=self.lineEdit_label5.text()

        labels=[label1,label2,label3,label4,label5]


    def title(self):
        title=self.lineEdit_title.text()


    def introduction(self):
        introduction=self.textEdit_2.toPlainText()

    def subtitle(self):

        doc=self.subtitle_textedit.toPlainText()
        with open(r'.\sbtitle\{}.srt','w') as f:
            f.write(doc)


    def header(self):
        header=str(self.header_choice.currentText())

    def logo(self):
        logo=str(self.logo_choice.currentText())

    def remote_connect_panel(self):
        pass

    def setting_panel(self):
        self.dialog= window=QtWidgets.QDialog()
        setting_ui=setting1.Ui_Dialog()
        setting_ui.setupUi(self.dialog)
        self.dialog.show()
        # pass

    def cell_was_clicked(self, row, column):
        # print("Row %d and Column %d was clicked" % (row, column))
        item = self.video_list.itemAt(0, column)
        self.en_title = item.text()




    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1022, 732)
        self.top_vertical = QtWidgets.QWidget(Form)
        self.top_vertical.setGeometry(QtCore.QRect(9, 9, 1009, 720))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.top_vertical.setFont(font)
        self.top_vertical.setObjectName("top_vertical")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.top_vertical)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_horizontalFrame = QtWidgets.QFrame(self.top_vertical)
        self.top_horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.top_horizontalFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_horizontalFrame.setObjectName("top_horizontalFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.top_horizontalFrame)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.icon = QtWidgets.QFrame(self.top_horizontalFrame)
        self.icon.setMinimumSize(QtCore.QSize(48, 48))
        self.icon.setStyleSheet("image: url(:/image/icon.jpg);")
        self.icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon.setObjectName("icon")
        self.horizontalLayout_4.addWidget(self.icon)
        spacerItem = QtWidgets.QSpacerItem(300, 40, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.remote_connect = QtWidgets.QPushButton(self.top_horizontalFrame)
        self.remote_connect.setObjectName("remote_connect")
        self.horizontalLayout_4.addWidget(self.remote_connect)
        #####################################################
        #
        self.setting = QtWidgets.QPushButton(self.top_horizontalFrame)
        self.setting.setObjectName("setting")
        self.setting.clicked.connect(self.setting_panel)

        self.horizontalLayout_4.addWidget(self.setting)
        self.upload = QtWidgets.QPushButton(self.top_horizontalFrame)
        self.upload.setObjectName("upload")
        self.horizontalLayout_4.addWidget(self.upload)
        self.all_in_one = QtWidgets.QPushButton(self.top_horizontalFrame)
        self.all_in_one.setWhatsThis("")
        self.all_in_one.setObjectName("all_in_one")
        self.horizontalLayout_4.addWidget(self.all_in_one)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.top_horizontalFrame)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout_4.addWidget(self.commandLinkButton)
        self.mini = QtWidgets.QPushButton(self.top_horizontalFrame)
        self.mini.setInputMethodHints(QtCore.Qt.ImhExclusiveInputMask)
        self.mini.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("components/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mini.setIcon(icon)
        self.mini.setIconSize(QtCore.QSize(32, 32))
        self.mini.setShortcut("")
        self.mini.setFlat(True)
        self.mini.setObjectName("mini")
        self.horizontalLayout_4.addWidget(self.mini)
        self.close = QtWidgets.QPushButton(self.top_horizontalFrame)
        self.close.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("components/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon1)
        self.close.setIconSize(QtCore.QSize(32, 32))
        self.close.setShortcut("")
        self.close.setFlat(True)
        self.close.setObjectName("close")
        self.horizontalLayout_4.addWidget(self.close)
        self.verticalLayout.addWidget(self.top_horizontalFrame)
        self.horizontalFrame = QtWidgets.QFrame(self.top_vertical)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.displayer = QtWidgets.QFrame(self.horizontalFrame)
        self.displayer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.displayer.setObjectName("displayer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.displayer)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.displayer)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.video_list = QtWidgets.QTableWidget(self.tab)
        self.video_list.setGeometry(QtCore.QRect(0, 0, 451, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_list.sizePolicy().hasHeightForWidth())
        self.video_list.setSizePolicy(sizePolicy)
        self.video_list.setMinimumSize(QtCore.QSize(0, 0))
        self.video_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.video_list.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.video_list.setObjectName("video_list")
        self.video_list.setColumnCount(4)
        self.video_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.video_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_list.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.video_list_by_channel = QtWidgets.QTableWidget(self.tab_2)
        self.video_list_by_channel.setGeometry(QtCore.QRect(0, 20, 451, 511))
        self.video_list_by_channel.setMinimumSize(QtCore.QSize(0, 0))
        self.video_list_by_channel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.video_list_by_channel.setObjectName("video_list_by_channel")
        self.video_list_by_channel.setColumnCount(4)
        self.video_list_by_channel.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.video_list_by_channel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_list_by_channel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_list_by_channel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_list_by_channel.setHorizontalHeaderItem(3, item)
        self.video_channel_choice = QtWidgets.QComboBox(self.tab_2)
        self.video_channel_choice.setGeometry(QtCore.QRect(0, 0, 301, 22))
        self.video_channel_choice.setObjectName("video_channel_choice")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.header_and_logo = QtWidgets.QListView(self.tab_3)
        self.header_and_logo.setGeometry(QtCore.QRect(0, 0, 451, 521))
        self.header_and_logo.setObjectName("header_and_logo")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.displayer)
        self.editor = QtWidgets.QFrame(self.horizontalFrame)
        self.editor.setObjectName("editor")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.editor)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.editor_grid = QtWidgets.QGridLayout()
        self.editor_grid.setSpacing(3)
        self.editor_grid.setObjectName("editor_grid")
        self.sub_function_exec = QtWidgets.QHBoxLayout()
        self.sub_function_exec.setSpacing(3)
        self.sub_function_exec.setObjectName("sub_function_exec")
        self.praser = QtWidgets.QPushButton(self.editor)
        self.praser.setObjectName("praser")
        self.sub_function_exec.addWidget(self.praser)
        self.ptube = QtWidgets.QPushButton(self.editor)
        self.ptube.setObjectName("ptube")
        self.sub_function_exec.addWidget(self.ptube)
        self.edit = QtWidgets.QPushButton(self.editor)
        self.edit.setObjectName("edit")
        self.sub_function_exec.addWidget(self.edit)
        self.editor_grid.addLayout(self.sub_function_exec, 0, 0, 1, 1)
        self.video_title_subtitle_edit = QtWidgets.QVBoxLayout()
        self.video_title_subtitle_edit.setSpacing(2)
        self.video_title_subtitle_edit.setObjectName("video_title_subtitle_edit")
        #################################################

        self.title_label = QtWidgets.QLabel(self.editor)
        self.title_label.setObjectName("title_label")
        self.video_title_subtitle_edit.addWidget(self.title_label)
        self.lineEdit_title = QtWidgets.QLineEdit(self.editor)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.video_title_subtitle_edit.addWidget(self.lineEdit_title)
        self.subtitle_label = QtWidgets.QLabel(self.editor)
        self.subtitle_label.setObjectName("subtitle_label")
        self.video_title_subtitle_edit.addWidget(self.subtitle_label)
        self.subtitle_textBrowser = QtWidgets.QTextBrowser(self.editor)
        self.subtitle_textBrowser.setObjectName("subtitle_textBrowser")
        self.video_title_subtitle_edit.addWidget(self.subtitle_textBrowser)
        self.subtitle_textedit = QtWidgets.QTextEdit(self.editor)
        self.subtitle_textedit.setObjectName("subtitle_textedit")
        self.video_title_subtitle_edit.addWidget(self.subtitle_textedit)
        self.save = QtWidgets.QPushButton(self.editor)
        self.save.setObjectName("save")
        self.video_title_subtitle_edit.addWidget(self.save)
        self.editor_grid.addLayout(self.video_title_subtitle_edit, 8, 0, 1, 1)
        self.video_label_intro_edit = QtWidgets.QVBoxLayout()
        self.video_label_intro_edit.setSpacing(2)
        self.video_label_intro_edit.setObjectName("video_label_intro_edit")
        self.video_labels = QtWidgets.QLabel(self.editor)
        self.video_labels.setMaximumSize(QtCore.QSize(16777215, 30))
        self.video_labels.setObjectName("video_labels")
        self.video_label_intro_edit.addWidget(self.video_labels)
        self.lineEdit_label1 = QtWidgets.QLineEdit(self.editor)
        self.lineEdit_label1.setObjectName("lineEdit_label1")
        self.video_label_intro_edit.addWidget(self.lineEdit_label1)
        self.lineEdit_label2 = QtWidgets.QLineEdit(self.editor)
        self.lineEdit_label2.setObjectName("lineEdit_label2")
        self.video_label_intro_edit.addWidget(self.lineEdit_label2)
        self.lineEdit_label3 = QtWidgets.QLineEdit(self.editor)
        self.lineEdit_label3.setObjectName("lineEdit_label3")
        self.video_label_intro_edit.addWidget(self.lineEdit_label3)
        self.lineEdit_label4 = QtWidgets.QLineEdit(self.editor)
        self.lineEdit_label4.setObjectName("lineEdit_label4")
        self.video_label_intro_edit.addWidget(self.lineEdit_label4)
        self.lineEdit_label5 = QtWidgets.QLineEdit(self.editor)
        self.lineEdit_label5.setObjectName("lineEdit_label5")
        self.video_label_intro_edit.addWidget(self.lineEdit_label5)
        self.header_choice_label = QtWidgets.QLabel(self.editor)
        self.header_choice_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.header_choice_label.setObjectName("header_choice_label")
        self.video_label_intro_edit.addWidget(self.header_choice_label)
        self.header_choice = QtWidgets.QComboBox(self.editor)
        self.header_choice.setObjectName("header_choice")
        self.video_label_intro_edit.addWidget(self.header_choice)
        self.logo_choice_label = QtWidgets.QLabel(self.editor)
        self.logo_choice_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.logo_choice_label.setObjectName("logo_choice_label")
        self.video_label_intro_edit.addWidget(self.logo_choice_label)
        self.logo_choice = QtWidgets.QComboBox(self.editor)
        self.logo_choice.setObjectName("logo_choice")
        self.video_label_intro_edit.addWidget(self.logo_choice)
        self.introdunction_choice_label = QtWidgets.QLabel(self.editor)
        self.introdunction_choice_label.setObjectName("introdunction_choice_label")
        self.video_label_intro_edit.addWidget(self.introdunction_choice_label)
        self.textEdit_2 = QtWidgets.QTextEdit(self.editor)
        self.textEdit_2.setObjectName("textEdit_2")
        self.video_label_intro_edit.addWidget(self.textEdit_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.editor)
        self.pushButton_6.setObjectName("pushButton_6")
        self.video_label_intro_edit.addWidget(self.pushButton_6)
        self.editor_grid.addLayout(self.video_label_intro_edit, 8, 2, 1, 1)
        self.video_default = QtWidgets.QHBoxLayout()
        self.video_default.setSpacing(3)
        self.video_default.setObjectName("video_default")
        self.no_title = QtWidgets.QRadioButton(self.editor)
        self.no_title.setObjectName("no_title")
        self.video_default.addWidget(self.no_title)
        self.default_2 = QtWidgets.QRadioButton(self.editor)
        self.default_2.setObjectName("default_2")
        self.video_default.addWidget(self.default_2)
        self.editor_grid.addLayout(self.video_default, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.editor_grid)
        self.horizontalLayout.addWidget(self.editor)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.end_horizontalFrame = QtWidgets.QFrame(self.top_vertical)
        self.end_horizontalFrame.setMinimumSize(QtCore.QSize(1, 80))
        self.end_horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.end_horizontalFrame.setObjectName("end_horizontalFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.end_horizontalFrame)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.remote = QtWidgets.QTextBrowser(self.end_horizontalFrame)
        self.remote.setObjectName("remote")
        self.gridLayout_2.addWidget(self.remote, 1, 1, 1, 1)
        self.local = QtWidgets.QTextBrowser(self.end_horizontalFrame)
        self.local.setObjectName("local")
        self.gridLayout_2.addWidget(self.local, 1, 0, 1, 1)
        self.local_info = QtWidgets.QLabel(self.end_horizontalFrame)
        self.local_info.setObjectName("local_info")
        self.gridLayout_2.addWidget(self.local_info, 0, 0, 1, 1)
        self.remote_info = QtWidgets.QLabel(self.end_horizontalFrame)
        self.remote_info.setObjectName("remote_info")
        self.gridLayout_2.addWidget(self.remote_info, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.end_horizontalFrame)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.remote_connect.setToolTip(_translate("Form", "连接远程主机\n"
""))
        self.remote_connect.setText(_translate("Form", "remote server"))
        self.setting.setToolTip(_translate("Form", "管理解析地址和上传插件"))
        self.setting.setText(_translate("Form", "setting"))
        self.upload.setText(_translate("Form", "upload"))
        self.all_in_one.setToolTip(_translate("Form", "一键以默认设置执行"))
        self.all_in_one.setText(_translate("Form", "all in one"))
        self.commandLinkButton.setText(_translate("Form", "CommandLinkButton"))
        item = self.video_list.horizontalHeaderItem(0)
        item.setText(_translate("Form", "title"))
        item = self.video_list.horizontalHeaderItem(1)
        item.setText(_translate("Form", "url"))
        item = self.video_list.horizontalHeaderItem(2)
        item.setText(_translate("Form", "length"))
        item = self.video_list.horizontalHeaderItem(3)
        item.setText(_translate("Form", "loaded time"))
        ##################################################
        # add video items

        title,url=utils.video_list()
        for i,x,y in enumerate([title,url]):
            item=self.video_list.verticalHeaderItem(i)
            item.setText('{}'.format(x))
            item.setText('{}'.format(y))

        self.video_list.cellClicked.connect(self.cell_was_clicked)



        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "video list"))
        item = self.video_list_by_channel.horizontalHeaderItem(0)
        item.setText(_translate("Form", "title"))
        item = self.video_list_by_channel.horizontalHeaderItem(1)
        item.setText(_translate("Form", "url"))
        item = self.video_list_by_channel.horizontalHeaderItem(2)
        item.setText(_translate("Form", "length"))
        item = self.video_list_by_channel.horizontalHeaderItem(3)
        item.setText(_translate("Form", "loaded time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "channel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "header-logo"))
        self.praser.setText(_translate("Form", "praser"))
        self.ptube.setText(_translate("Form", "pytube"))
        self.edit.setText(_translate("Form", "edit"))
        ####################################################
        # set title_label content as en_title
        self.title_label.setText(_translate("Form", "title: {}".format(self.en_title)))


        self.subtitle_label.setText(_translate("Form", "video subtitle"))
        self.save.setText(_translate("Form", "save"))
        self.video_labels.setText(_translate("Form", "video labels"))
        self.header_choice_label.setText(_translate("Form", "header chice"))
        self.logo_choice_label.setText(_translate("Form", "logo chice"))
        self.introdunction_choice_label.setText(_translate("Form", "video introduction"))
        self.pushButton_6.setText(_translate("Form", "submit"))
        self.no_title.setText(_translate("Form", "no title"))
        self.default_2.setToolTip(_translate("Form", "using default label\\introduction"))
        self.default_2.setText(_translate("Form", "default"))
        self.local_info.setText(_translate("Form", "local info"))
        self.remote_info.setText(_translate("Form", "remote info"))

# import images_rc
if __name__=='__main__':
    import sys
    app=QtWidgets.QApplication(sys.argv)
    window=QtWidgets.QWidget()
    ui=Ui_Form()
    ui.setupUi(window)
    # window.setFixedHeight(700)
    # window.setFixedWidth(1000)
    window.setWindowFlags(Qt.FramelessWindowHint)

    window.show()

    app.exec_()